create database QLHH on primary
(
	name='QLHH_Primary',
	filename='E:\QLHH\QLHH.mdf',
	size=20MB,
	maxsize=100MB,
	filegrowth=20%
)
log on
(
	name='QLHH_Log',
	filename='E:\QLHH\QLHH.ldf',
	size=5MB,
	maxsize=20MB,
	filegrowth=10%
);
go

use QLHH
go
sp_spaceused

CREATE TABLE HANGHOA
(
	MAHG CHAR(10),
	TENHG NVARCHAR(30),
	DVT NVARCHAR(8),
	DONGIA MONEY,
	COHANG BIT,
	CONSTRAINT PK_HANGHOA PRIMARY KEY (MAHG)
)
CREATE TABLE KHACH
(
	MAKH CHAR(10),
	HOTEN NVARCHAR(30),
	DCHI NVARCHAR(50),
	DAILY NVARCHAR(30),
	SODT CHAR(30),
	CONSTRAINT PK_KHACH PRIMARY KEY (MAKH)
)
CREATE TABLE HOADON
(
	SOHD CHAR(10),
	NGAYLAP DATETIME,
	NGAYGIAO DATETIME,
	TRIGIA MONEY,
	MAKH CHAR(10),
	CONSTRAINT PK_HOADON PRIMARY KEY (SOHD),
	CONSTRAINT FK_HOADON_KHACH FOREIGN KEY (MAKH) REFERENCES KHACH(MAKH)
)
CREATE TABLE CHITIET_HD
(
	SOHD CHAR(10),
	MAHG CHAR(10),
	SOLUONG TINYINT,
	GIABAN MONEY,
	CONSTRAINT PK_CHITIET_HD PRIMARY KEY (SOHD, MAHG),
	CONSTRAINT FK_CHITIET_HD_HOADON FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	CONSTRAINT FK_CHITIET_HD_HANGHOA FOREIGN KEY (MAHG) REFERENCES HANGHOA(MAHG)
)
go

