CREATE TABLE LOP(
	MALOP NCHAR(10) NOT NULL,
	TENLOP NVARCHAR(50),
	SISO INT,
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
)
CREATE TABLE SINHVIEN(
	MASV NCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50),
	NGAYSINH DATETIME,
	MALOP NCHAR(10),
	PRIMARY KEY(MASV),  -- khoá chính
	FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
)